name: Build CachyOS ISO

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pacman -Sy --noconfirm archlinux-keyring
          pacman -Syu --noconfirm
          pacman -Sy --noconfirm archiso squashfs-tools xorriso sudo

      - name: Disable SigLevel
        run: |
          sed -i 's/^SigLevel.*/SigLevel = Never/' etc/pacman.conf || true

      - name: Build ISO
        run: |
          sudo ./buildiso.sh -p desktop -v

      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: cachyos-iso
          path: out/*.iso
